import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { AdminReportTabValue } from "../components/AdminReportsTabs"
import { AdminReportsCommunityStats, AdminReportsFoodStats, AdminReportsOverviewStats, AdminReportsSeasonalStats } from "../types/adminReports.types"
import { fetchAdminReportsCommunity, fetchAdminReportsFood, fetchAdminReportsOverview, fetchAdminReportsSeasonal } from "./adminReports.service"

export type AdminReportsPdfExportMode = "current" | "full"

interface ExportAdminReportsPdfParams {
    activeTab: AdminReportTabValue
    exportMode: AdminReportsPdfExportMode
    adminName: string
    overview?: AdminReportsOverviewStats | null
    community?: AdminReportsCommunityStats | null
    food?: AdminReportsFoodStats | null
    seasonal?: AdminReportsSeasonalStats | null
}

const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const MARGIN_X = 14

function paintBackground(doc: jsPDF) {
    // doc.setFillColor(13, 14, 17)
    // doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, "F")
}

function getReportTitle(activeTab: AdminReportTabValue, exportMode: AdminReportsPdfExportMode) {
    if (exportMode === "full") return "Full Reports Dashboard"

    if (activeTab === "overview") return "Overview Report"
    if (activeTab === "community") return "Community Activity Report"
    if (activeTab === "food") return "Food Insights Report"

    return "Seasonal Trends Report"
}

function shouldExportSection(
    section: AdminReportTabValue,
    activeTab: AdminReportTabValue,
    exportMode: AdminReportsPdfExportMode
) {
    return exportMode === "full" || activeTab === section
}

function addFooter(doc: jsPDF, generatedAt: string) {
    doc.setDrawColor(60)
    doc.line(MARGIN_X, PAGE_HEIGHT - 18, PAGE_WIDTH - MARGIN_X, PAGE_HEIGHT - 18)

    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text("FlavorFolio Admin Reports", MARGIN_X, PAGE_HEIGHT - 10)
    doc.text(generatedAt, PAGE_WIDTH - MARGIN_X, PAGE_HEIGHT - 10, {
        align: "right",
    })  
}

function addHeader(doc: jsPDF, title: string, adminName: string, generatedAt: string) {
    doc.setTextColor(33, 37, 41)
    doc.setFontSize(12)
    doc.text("FlavorFolio Admin Report", MARGIN_X, 18)

    doc.setTextColor(33, 37, 41)
    doc.setFontSize(24)
    doc.text(title, MARGIN_X, 31)

    doc.setTextColor(107, 114, 128)
    doc.setFontSize(10)
    doc.text(`Generated by: ${adminName}`, MARGIN_X, 41)
    doc.text(`Generated at: ${generatedAt}`, MARGIN_X, 47)

    return 60
}

function table(doc: jsPDF, startY: number, head: string[][], body: any[][]) {
    const tableStartPage = doc.getNumberOfPages()

    autoTable(doc, {
        startY,
        head,
        body,
        theme: "grid",
        styles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontSize: 9,
        },
        headStyles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontStyle: "bold",
        },
        willDrawPage: () => {
            const currentPage = doc.getCurrentPageInfo().pageNumber

            if (currentPage > tableStartPage) {
                paintBackground(doc)
            }
        },
    })

    return (doc as any).lastAutoTable.finalY + 12
}

function sectionTitle(doc: jsPDF, title: string, y: number) {
    doc.setFontSize(15)
    doc.setTextColor(33, 37, 41)
    doc.text(title, MARGIN_X, y)
    return y + 7
}

export async function fetchFullAdminReports() {
  const [
    overview,
    community,
    food,
    seasonal,
  ] = await Promise.all([
    fetchAdminReportsOverview(),
    fetchAdminReportsCommunity(),
    fetchAdminReportsFood(),
    fetchAdminReportsSeasonal(),
  ])

  return {
    overview,
    community,
    food,
    seasonal,
  }
}

export function exportAdminReportsPdf({
    activeTab,
    exportMode,
    adminName,
    overview,
    community,
    food,
    seasonal,
}: ExportAdminReportsPdfParams) {
    const doc = new jsPDF("p", "mm", "a4")

    const generatedAt = new Intl.DateTimeFormat("en-US", {
        dateStyle: "medium",
        timeStyle: "short",
    }).format(new Date())

    paintBackground(doc)

    let y = addHeader(
        doc,
        getReportTitle(activeTab, exportMode),
        adminName,
        generatedAt
    )

    if (shouldExportSection("overview", activeTab, exportMode) && overview) {
        y = sectionTitle(doc, "Metrics Overview", y)

        y = table(
        doc,
        y,
        [["Metric", "Value"]],
            [
                ["Users", overview.totalUsers],
                ["Recipes", overview.totalRecipes],
                ["Comments", overview.totalComments],
                ["Saved Recipes", overview.totalSaves],
                ["Average Rating", overview.averageRating.toFixed(2)],
                ["New Users / 30d", overview.newUsers30d],
                ["New Recipes / 30d", overview.newRecipes30d],
                ["Published Recipes %", `${overview.publishedRecipesPercent.toFixed(1)}%`],
            ]
        )

        y = sectionTitle(doc, "Most Saved Recipes", y)

        y = table(
        doc,
        y,
            [["#", "Recipe", "Author", "Saves"]],
            overview.topSavedRecipes.map((recipe, index) => [
                index + 1,
                recipe.title,
                recipe.authorUsername,
                recipe.savesCount,
            ])
        )

        y = sectionTitle(doc, "Flavor Insights", y)

        table(
        doc,
        y,
            [["Insight"]],
            overview.flavorInsights.map((insight) => [insight.text])
        )
    }

    if (shouldExportSection("community", activeTab, exportMode) && community) {
        y = sectionTitle(doc, "Monthly Community Activity", y)

        table(
        doc,
        y,
            [["Month", "Recipes", "Users", "Saves", "Comments"]],
            community.monthlyActivity.map((item) => [
                item.label,
                item.recipes,
                item.users,
                item.saves,
                item.comments,
            ])
        )
    }

    if (shouldExportSection("food", activeTab, exportMode) && food) {
        y = sectionTitle(doc, "Most Used Cuisines", y)

        y = table(
        doc,
        y,
            [["Cuisine", "Recipes"]],
            food.topCuisines.map((item) => [item.name, item.value])
        )

        y = sectionTitle(doc, "Most Used Meal Types", y)

        y = table(
        doc,
        y,
            [["Meal Type", "Recipes"]],
            food.mealTypes.map((item) => [item.name, item.value])
        )

        y = sectionTitle(doc, "Difficulty Distribution", y)

        y = table(
        doc,
        y,
            [["Difficulty", "Recipes"]],
            food.difficultyDistribution.map((item) => [item.name, item.value])
        )

        y = sectionTitle(doc, "Average Cooking Time", y)

        y = table(
        doc,
        y,
            [["Duration", "Recipes"]],
            food.cookingTimeDistribution.map((item) => [item.label, item.value])
        )

        y = sectionTitle(doc, "Top 20 Ingredients", y)

        table(
        doc,
        y,
            [["Ingredient", "Appearances"]],
            food.topIngredients.slice(0, 20).map((item) => [item.name, item.value])
        )
    }

    if (shouldExportSection("seasonal", activeTab, exportMode) && seasonal) {
        y = sectionTitle(doc, "Top Ingredient by Month", y)

        y = table(
        doc,
        y,
        [["Month", "Ingredient", "Count"]],
        seasonal.topIngredientByMonth.map((item) => [
            item.month,
            item.ingredient,
            item.count,
        ])
        )

        y = sectionTitle(doc, "Seasonal Ingredient Trends", y)

        table(
        doc,
        y,
        [["Season", "Ingredient", "Count"]],
        seasonal.seasonalGroups.flatMap((group) =>
            group.ingredients.map((item) => [
            group.season,
            item.ingredient,
            item.count,
            ])
        )
        )
    }

    const pageCount = doc.getNumberOfPages()

    for (let page = 1; page <= pageCount; page += 1) {
        doc.setPage(page)
        addFooter(doc, generatedAt)
    }

    doc.save(`flavorfolio-${exportMode === "full" ? "full" : activeTab}-report-${Date.now()}.pdf`)
}