import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { AdminDashboardModerationActivity, AdminDashboardStats } from "../types/adminDashboard.types"

interface ExportAdminDashboardPdfParams {
  stats: AdminDashboardStats
  adminName: string
  timeRangeLabel: string
}

function formatNumber(value: number) {
  return new Intl.NumberFormat("en-US").format(value)
}

const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const MARGIN_X = 14

function paintPageBackground(doc: jsPDF) {
    doc.setFillColor(255, 255, 255)
    doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, "F")
}

function addFooter(doc: jsPDF, generatedAt: string) {
    doc.setDrawColor(60)
    doc.line(MARGIN_X, PAGE_HEIGHT - 18, PAGE_WIDTH - MARGIN_X, PAGE_HEIGHT - 18)

    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text("FlavorFolio Admin Dashboard Report", MARGIN_X, PAGE_HEIGHT - 10)
    doc.text(generatedAt, PAGE_WIDTH - MARGIN_X, PAGE_HEIGHT - 10, { align: "right" })
}

function ensureSpace(doc: jsPDF, currentY: number, neededHeight: number, generatedAt: string) {
    if (currentY + neededHeight <= PAGE_HEIGHT - 24) return currentY

    addFooter(doc, generatedAt)
    doc.addPage()
    paintPageBackground(doc)

    return 18
}

function addSectionTitle(
    doc: jsPDF,
    y: number,
    title: string,
    description: string
) {
    doc.setFontSize(15)
    doc.setTextColor(255, 255, 255)
    doc.text(title, MARGIN_X, y)

    doc.setFontSize(10)
    doc.setTextColor(168, 179, 207)
    doc.text(description, MARGIN_X, y + 6)

    return y + 11
}

function getModerationActivityLabel(
  type: AdminDashboardModerationActivity["type"]
) {
  if (type === "approved") return "Recipe approved"
  if (type === "needs_revision") return "Recipe needs revision"
  return "Recipe resubmitted"
}

function formatDateTime(ms: number) {
  if (!ms) return "-"

  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(ms))
}

export function exportAdminDashboardSummaryPdf({
  stats,
  adminName,
  timeRangeLabel,
}: ExportAdminDashboardPdfParams) {
    const doc = new jsPDF("p", "mm", "a4")
    paintPageBackground(doc)

    const generatedAt = new Intl.DateTimeFormat("en-US", {
        dateStyle: "medium",
        timeStyle: "short",
    }).format(new Date())

    doc.setTextColor(33, 37, 41)
    doc.setFontSize(12)
    doc.text("FlavorFolio Admin Report", 14, 18)

    doc.setTextColor(33, 37, 41)
    doc.setFontSize(24)
    doc.text("Dashboard Summary", 14, 30)

    doc.setTextColor(107, 114, 128)
    doc.setFontSize(10)
    doc.text(`Generated by: ${adminName}`, 14, 39)
    doc.text(`Generated at: ${generatedAt}`, 14, 45)
    doc.text(`Range: ${timeRangeLabel}`, 14, 51)

    doc.setFontSize(15)
    doc.setTextColor(33, 37, 41)
    doc.text("Metrics Overview", 14, 58)
    
    doc.setFontSize(10)
    doc.setTextColor(107, 114, 128)
    doc.text(
        "High-level platform statistics for the selected time range.",
        14,
        64
    )

    autoTable(doc, {
        startY: 69,
        head: [["Metric", "Value"]],
        body: [
        ["Total Users", formatNumber(stats.totalUsers)],
        ["Total Recipes", formatNumber(stats.totalRecipes)],
        ["Published Recipes", formatNumber(stats.publishedRecipes)],
        ["Pending Reviews", formatNumber(stats.pendingRecipes)],
        ["Needs Revision", formatNumber(stats.needsRevisionRecipes)],
        ["Total Saves", formatNumber(stats.totalSaves)],
        ["Total Comments", formatNumber(stats.totalComments)],
        ["Average Rating", stats.averageRating.toFixed(2)],
        ],
        theme: "grid",
        styles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontSize: 9,
        },
        headStyles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontStyle: "bold",
        },
    })

    const statusY = (doc as any).lastAutoTable.finalY + 12

    doc.setFontSize(15)
    doc.setTextColor(33, 37, 41)
    doc.text("Recipe Status Distribution", 14, statusY)  
    doc.setFontSize(10)
    doc.setTextColor(107, 114, 128)
    doc.text(
        "Current moderation status breakdown.",
        14,
        statusY + 6
    )

    autoTable(doc, {
        startY: statusY + 11,
        head: [["Status", "Count", "Percentage"]],
        body: stats.statusDistribution.map((item) => [
        item.label,
        String(item.value),
        stats.totalRecipes
            ? `${((item.value / stats.totalRecipes) * 100).toFixed(1)}%`
            : "0%",
        ]),
        theme: "grid",
        styles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontSize: 9,
        },
        headStyles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontStyle: "bold",
        },
    })

    const topRecipesY = (doc as any).lastAutoTable.finalY + 12

    doc.setFontSize(15)
    doc.setTextColor(33, 37, 41)
    doc.text("Top Saved Recipes",14,topRecipesY)
    
    doc.setFontSize(10)
    doc.setTextColor(107, 114, 128)
    doc.text(
        "Most bookmarked recipes.",
        14,
        topRecipesY + 6
    )

    autoTable(doc, {
        startY: topRecipesY + 11,
        head: [["#", "Recipe", "Author", "Saves"]],
        body: stats.topSavedRecipes.map((recipe, index) => [
        String(index + 1),
        recipe.title,
        recipe.authorUsername,
        String(recipe.savesCount),
        ]),
        theme: "grid",
        styles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontSize: 9,
        },
        headStyles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontStyle: "bold",
        },
    })

    let moderationY = (doc as any).lastAutoTable.finalY + 12

    moderationY = ensureSpace(doc, moderationY, 55, generatedAt)

    const moderationTableY = addSectionTitle(
        doc,
        moderationY,
        "Recent Moderation Activity",
        "Latest approval and revision actions performed by moderators."
    )


    autoTable(doc, {
        startY: moderationTableY,
        head: [["Activity", "Recipe", "Time"]],
        body: stats.recentModerationActivity.map((activity) => [
            getModerationActivityLabel(activity.type),
            activity.recipeTitle,
            formatDateTime(activity.createdAtMs),
        ]),
        theme: "grid",
        styles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontSize: 9,
        },
        headStyles: {
            fillColor: [255, 255, 255],
            textColor: [33, 37, 41],
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
            fontStyle: "bold",
        },
    })

    const pageCount = doc.getNumberOfPages()

    for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
        doc.setPage(pageNumber)
        addFooter(doc, generatedAt)
    }

    doc.save(`flavorfolio-admin-report-${Date.now()}.pdf`)
}